### ISSUE TITLE
Korean translation link on README.md causes 404 error.

### ISSUE THREAD

**Issue by nemorize** [Sharlottes/judgekit#1]
`./readmes/README_ko.md` has been moved to `./doc/readmes/README_ko.md` at d80ea27.
But the link on `./README.md` has not been updated.

https://github.com/Sharlottes/judgekit/blob/918c7ef51712b60b24315cb328da838ebbacdc94/README.md?plain=1#L11

should be
`\- [한국어](https://github.com/Sharlottes/judgekit/blob/master/doc/readmes/README_ko.md) \-`

👍

**Comment by Sharlottes** [comment]
https://github.com/Sharlottes/judgekit/commit/20a07d35f5ea07213675e5a9c20286953f302acc
fixed, thanks for your feedback!
